---

- hosts: firstservers
  tasks:
  - name: update and upgrade apt packages
    apt:
          update_cache: yes
          upgrade: 'yes'
          autoremove: yes
          autoclean: yes

  - name: Install sudo
    ansible.builtin.package:
      name: sudo
      state: present
    become: yes
    become_method: su

  - name: Add user 'debian' to sudo
    command: usermod -aG sudo debian
    become: yes
    become_method: su
    become_exe: 'su -'
